import type { NextPage } from 'next'
import Head from 'next/head'
import CardProfile from '../components/CardProfile'
import Warpper from '../components/Warpper'

const Home: NextPage = () => {
  return (
    <div className="app m-0 p-0 bg-gray-800">
      <Head>
        <title>Thanonphat Space 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@300;400;500&display=swap" rel="stylesheet" />
      </Head>

      <main className="h-full w-full">
        <Warpper />
        <div className="w-full flex flex-col justify-center items-center gap-8">
          <div className="mt-8">
            <CardProfile />
          </div>
          <div></div>
        </div>
      </main>
    </div>
  )
}

export default Home
